// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shree_om.Data;

#nullable disable

namespace shree_om.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320145249_AddWishlist")]
    partial class AddWishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("shree_om.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Premium door handle collection",
                            Name = "Door Handles"
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-security lock systems",
                            Name = "Locks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Durable hinge solutions",
                            Name = "Hinges"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tower bolt collection",
                            Name = "Tower Bolts"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hardware accessories",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("shree_om.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("shree_om.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "yashimakwana2275",
                            ItemCount = 1,
                            OrderDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2025-PUD268CBO",
                            Status = "Pending",
                            TotalAmount = 1061m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "yashimakwana2275",
                            ItemCount = 1,
                            OrderDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2025-EZ6XZAXH2",
                            Status = "Pending",
                            TotalAmount = 1475m
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Rajesh Kumar",
                            ItemCount = 2,
                            OrderDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-001",
                            Status = "Delivered",
                            TotalAmount = 3597m
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Priya Sharma",
                            ItemCount = 2,
                            OrderDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-002",
                            Status = "Shipped",
                            TotalAmount = 2250m
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "Amit Patel",
                            ItemCount = 1,
                            OrderDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-003",
                            Status = "Processing",
                            TotalAmount = 899m
                        },
                        new
                        {
                            Id = 6,
                            CustomerName = "Suresh Kumar",
                            ItemCount = 3,
                            OrderDate = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-004",
                            Status = "Pending",
                            TotalAmount = 4580m
                        },
                        new
                        {
                            Id = 7,
                            CustomerName = "Neha Gupta",
                            ItemCount = 1,
                            OrderDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-005",
                            Status = "Delivered",
                            TotalAmount = 1798m
                        });
                });

            modelBuilder.Entity("shree_om.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality stainless steel SS304 door handle with chrome finish. Perfect for residential and commercial applications.",
                            DiscountPercent = 25,
                            Finish = "",
                            ImageUrl = "/images/handle-chrome.jpg",
                            IsFeatured = true,
                            Material = "",
                            Name = "Premium SS304 Door Handle – Chrome",
                            OriginalPrice = 1200m,
                            Price = 899m,
                            Rating = 4.5m,
                            ReviewCount = 156,
                            Stock = 234
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sleek matte black door handle for modern interiors. SS304 grade stainless steel.",
                            DiscountPercent = 75,
                            Finish = "",
                            ImageUrl = "/images/handle-black.jpg",
                            IsFeatured = true,
                            Material = "",
                            Name = "Premium SS304 Door Handle – Matt Black",
                            OriginalPrice = 1200m,
                            Price = 899m,
                            Rating = 4.5m,
                            ReviewCount = 156,
                            Stock = 234
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant gold finish door handle for luxury interiors.",
                            DiscountPercent = 25,
                            Finish = "",
                            ImageUrl = "/images/handle-gold.jpg",
                            IsFeatured = false,
                            Material = "",
                            Name = "Premium SS304 Door Handle – Gold",
                            OriginalPrice = 1200m,
                            Price = 899m,
                            Rating = 4.5m,
                            ReviewCount = 156,
                            Stock = 234
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium heavy-duty lock set for maximum security. Anti-pick, anti-drill design.",
                            DiscountPercent = 0,
                            Finish = "",
                            ImageUrl = "/images/lock-set.jpg",
                            IsFeatured = true,
                            Material = "",
                            Name = "Heavy Duty Lock Set Premium",
                            OriginalPrice = 1800m,
                            Price = 1250m,
                            Rating = 4.8m,
                            ReviewCount = 93,
                            Stock = 1196
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sleek matte black door handle for modern interiors.",
                            DiscountPercent = 21,
                            Finish = "",
                            ImageUrl = "/images/handle-mb.jpg",
                            IsFeatured = true,
                            Material = "",
                            Name = "Door Handle Matt Black Finish",
                            OriginalPrice = 749m,
                            Price = 749m,
                            Rating = 4.5m,
                            ReviewCount = 267,
                            Stock = 195
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Industrial-grade hinges. Corrosion-resistant. Sold as a pack of 2.",
                            DiscountPercent = 0,
                            Finish = "",
                            ImageUrl = "/images/hinge-set.jpg",
                            IsFeatured = true,
                            Material = "",
                            Name = "Heavy Duty Hinge Set (Pack of 2)",
                            OriginalPrice = 599m,
                            Price = 599m,
                            Rating = 4.6m,
                            ReviewCount = 421,
                            Stock = 1236
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium main door handle with multiple size and finish options. Ergonomic grip design.",
                            DiscountPercent = 11,
                            Finish = "",
                            ImageUrl = "/images/handle-smd.jpg",
                            IsFeatured = false,
                            Material = "",
                            Name = "Main Door Handle SMD-1012",
                            OriginalPrice = 899m,
                            Price = 749m,
                            Rating = 4.3m,
                            ReviewCount = 87,
                            Stock = 480
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium main door handle with multiple variants. Crafted for modern aesthetics and long-lasting durability.",
                            DiscountPercent = 11,
                            Finish = "",
                            ImageUrl = "/images/handle-smd2.jpg",
                            IsFeatured = false,
                            Material = "",
                            Name = "Premium Main Door Handle SMD-1007",
                            OriginalPrice = 899m,
                            Price = 799m,
                            Rating = 4.5m,
                            ReviewCount = 198,
                            Stock = 480
                        });
                });

            modelBuilder.Entity("shree_om.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("shree_om.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("shree_om.Models.Product", b =>
                {
                    b.HasOne("shree_om.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("shree_om.Models.WishlistItem", b =>
                {
                    b.HasOne("shree_om.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shree_om.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("shree_om.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
